---
title: 南开大学电子商城

product_privacy:
  price:
    default:  # product template
      default: false  # user role
      admin: true
      customer: true
      vendor: false
    computer:
      default: true

product_template:
  chem_reagent:
    title: 化学试剂
    query_placeholder: 请输入CAS号或其他关键字
    fields:
      cas_no:
        label: CAS号
        type: text
      mol_weight:
        label: 分子量
        type: text
      en_name:
        label: 英文名
        type: text
      mol_formula:
        label: 分子式
        type: number
      mol_aliases:
        label: 别名
        type: text
      danger_class:
        label: 危险品等级
        type: text  
  bio_reagent:
    title: 生物试剂
    fields:
      cas_no:
        label: CAS号
        type: text
      mol_weight:
        label: 分子量
        type: text
      en_name:
        label: 英文名
        type: text
      mol_formula:
        label: 分子式
        type: number
      mol_aliases:
        label: 别名
        type: text
      danger_class:
        label: 危险品分类
        type: text  
  consumable:
    title: 实验耗材
    fields:
  #small_device:
  #  title: 小型仪器
  #  fields:
  computer:
    title: 电脑整机
    fields:
      model:
        label: 型号
        type: text
      recommend_use:
        label: 推荐用途
        type: text
      os:
        label: 操作系统
        type: text
      cpu:
        label: CPU
        type: text
      memory:
        label: 内存
        type: text
      harddisk:
        label: 硬盘
        type: text
    
product_category:
  reagent: 
    title: 实验试剂
    sub:
      chem_reagent:
        title: 化学试剂
        template: chem_reagent
      bio_reagent:
        title: 生物试剂
        template: bio_reagent
  consumable:
    title: 实验耗材
    template: consumable
  equipment: 
    title: 仪器设备   
    sub:
    #  small_device:
    #    title: 小型仪器
    #    template: small_device
      computer:
        title: 电脑整机
        template: computer

product_criteria:
  chem_reagent:
    fields:
      chem_type:
        title: 试剂类别
        opts:
          1: 普通试剂
          2: 危险化学品
          3: 易制毒化学品
          4: 剧毒品
      price:
        title: 价格
        opts:
          1: 0~999
          2: 1000~1999
          3: 2000~2999
          4: 3000以上
  bio_reagent:
    fields:
      bio_transport_cond:
        title: 运输条件
        opts:
          1: 快递
          2: EMS
          3: 空运
          4: 海运
      bio_storage_cond:
        title: 存储条件
        opts:
          1: 常温
          2: 零下
          3: 工业冰箱
      price:
        title: 价格
        opts:
          1: 0~499
          2: 500~999
          3: 1000~1499
          4: 1500~1999
          5: 2000以上
  consumable:
    fields:
      price:
        title: 价格
        opts:
          1: 0~999
          2: 1000~1999
          3: 2000~2999
          4: 3000以上
  computer:
    fields:
      computer_type:
        title: 机型
        opts:
          1: 台式机
          2: 笔记本
          3: 一体机
          4: 工作基站
      cpu:
        title: CPU
        opts:
          1: haswell
          2: 酷睿i7 
          3: 酷睿i5
          4: 奔腾
          5: 赛扬
      memory:
        title: 内存
        opts:
          1: DDR
          2: DDR2
          3: DDR3
          4: DDR4
      disk:
        title: 硬盘
        opts:
          1: 320GB以下
          2: 500GB
          3: 750GB
          4: 1TB
          5: 2TB
          6: 3TB
          7: 3TB以上
      video_memory:
        title: 显寸
        opts:
          1: SDRAM
          2: SGRAM
          3: DDR
          4: DDR2
          5: DDR3
          6: VRAM
          7: WRAM
          8: RDRAM
      display:
        title: 显示器
        opts:
          1: 17英寸
          2: 19英寸
          3: 22英寸
          4: 23英寸
          5: 23.6英寸
          6: 24英寸
          7: 26英寸
          8: 27英寸及以上
      price:
        title: 价格
        opts:
          1: 0~1999
          2: 2000~2999
          3: 3000~4999
          4: 5000~7999
          5: 8000以上

rpc:
  default: 
    url: http://mall.nankai.edu.cn/api
    client_id: 51745fb57926407333591365bc64b0cf
    client_secret: 425802a7c0c585543477e0adc48303c5

...